Insert into LABELEVENTMAP (LABELEVENTMAPID,LABELEVENTID,LABELID,LABELCOUNT) values (1,1,1,1);
Insert into LABELEVENTMAP (LABELEVENTMAPID,LABELEVENTID,LABELID,LABELCOUNT) values (2,1,2,1);
Insert into LABELEVENTMAP (LABELEVENTMAPID,LABELEVENTID,LABELID,LABELCOUNT) values (3,1,3,2);
